site_name: Portal de Gobierno de IA - Centro de Excelencia
site_description: Portal integral para la adopción responsable y escalable de IA en banca mexicana
site_author: Centro de Excelencia de IA
site_url: https://ai-governance.banco.mx

# Repository
repo_name: gov-portal-full
repo_url: https://github.com/dannyawf/gov-portal-full
edit_uri: edit/main/docs/

# Copyright
copyright: |
  &copy; 2025 Centro de Excelencia de IA - Institución Bancaria Mexicana<br>
  <strong>CONFIDENCIAL Y PROPIETARIO</strong>

# Theme configuration
theme:
  name: material
  language: es
  logo: assets/images/nova-logo.svg
  favicon: assets/images/nova-logo.svg
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  
  font:
    text: Inter
    code: JetBrains Mono
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips

# Plugins
plugins:
  - search:
      lang: 
        - es
        - en
      separator: '[\s\-\.\_]'
      
  - tags

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: docs

# Extra CSS for Banking theme
extra_css:
  - stylesheets/nova-theme.css
  - stylesheets/banking-theme.css
  - stylesheets/dark-mode-corporate.css
  - stylesheets/contrast-fixes.css
  - stylesheets/mermaid-fixes.css
  - stylesheets/navigation-fixes.css

# Extra JavaScript for Mermaid diagrams
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/mermaid-config.js

# Navigation
nav:
  - 🏠 Inicio: index.md
  
  - 🚀 Empieza Aquí: start-here.md
  
  - 👨‍💻 Desarrolladores:
    - Onboarding:
      - Guía de Onboarding: developers/onboarding/guia-onboarding-desarrolladores.md
    - Guías de Instalación:
      - Instalación Nova-Cell: developers/guides/nova-cell-installation-guide.md
      - Entorno Local: developers/guides/local-development-setup.md
      - Mejores Prácticas: developers/guides/best-practices-ai-development.md
    - Academia de Desarrolladores:
      - Curriculum Completo: developers/academy/curriculum-desarrolladores-ai.md
    - Tutoriales:
      - Integración API: developers/tutorials/api-integration-guide.md
    - Referencia:
      - Troubleshooting y FAQ: developers/reference/troubleshooting-faq.md
  
  - 📊 IMPACT Dashboard:
    - Métricas de Valor: dashboard/impact-metrics.md
    - Demo Interactivo: dashboard/impact-demo.html
  
  - 🗺️ Journey de Adopción:
    - Vista General: journey/index.md
    - 1. Explorar: journey/explorar.md
    - 2. Experimentar: journey/experimentar.md
    - 3. Construir: journey/construir.md
    - 4. Validar: journey/validar.md
    - 5. Desplegar: journey/desplegar.md
    - 6. Escalar: journey/escalar.md
    - Green Paths:
      - Introducción: journey/green-paths/index.md
      - RAG Assistant: journey/green-paths/rag-assistant.md
      - Chatbot Call Center: journey/green-paths/chatbot-call-center.md
      - Document Classification: journey/green-paths/document-classification.md
      - Credit Scoring: journey/green-paths/credit-scoring.md
  
  - 🛠️ Servicios y Soporte:
    - Vista General: servicios/index.md
    - Catálogo de Servicios: servicios/catalogo-servicios.md
    - Evaluación de Modelos LLM: servicios/evaluacion-modelos-llm.md
    - Arquitecto de Adopción: servicios/arquitecto-adopcion.md
    - Plataforma Nova-Cell:
      - Hub Principal: servicios/plataforma/nova-cell-hub.md
      - CLI: servicios/plataforma/nova-cell-cli.md
      - Web UI: servicios/plataforma/nova-cell-webui.md
      - Knowledge Base: servicios/plataforma/nova-cell.md
    - Red Teaming IA: servicios/red-teaming.md
    - Solicitar Apoyo: servicios/solicitar-apoyo.md
  
  - 📚 Recursos y Conocimiento:
    - Academia:
      - Hub de Academia: recursos/academia/index.md
      - Rutas de Aprendizaje: recursos/academia/rutas-aprendizaje.md
      - Product Owner IA: recursos/academia/guia-capacitacion-product-owner-ia.md
      - Guía Desarrolladores IA: academy/guia-desarrolladores-ia.md
      - Guía Risk Officers IA: academy/guia-risk-officers-ia.md
      - Comunidad de Práctica: recursos/comunidad/index.md
    - Knowledge Hub:
      - Guía Principal: recursos/conocimiento/knowledge-hub-guide.md
      - Playbooks:
        - Hub de Playbooks: recursos/conocimiento/playbooks/index.md
        - Banca Digital IA: recursos/conocimiento/playbooks/playbook-banca-digital-ia.md
        - Risk Management IA: playbooks/playbook-risk-management-ia.md
        - Customer Service IA: playbooks/playbook-customer-service-ia.md
    - Patrones y Arquitecturas:
      - Arquitecturas de Referencia: recursos/patrones/arquitecturas-referencia.md
      - Arquitecturas Seguras: recursos/patrones/arquitecturas-seguras.md
    - Documentación Técnica:
      - API Documentation: technical/api-documentation.md
      - Nova-Cell Developer Guide: technical/nova-cell-developer-guide.md
      - MLOps Guide: recursos/documentacion-tecnica/mlops-guide.md
    - Herramientas:
      - AISIA Assessment: tools/aisia-assessment.md
      - ROI Calculator: tools/roi-calculator.md
      - Dashboard IMPACT: tools/dashboard-impact.md
      - Opportunity Radar: tools/opportunity-radar.md
  
  - 📊 Gobernanza y Compliance:
    - Políticas y Frameworks:
      - Uso Responsable de IA: gobernanza/politica-uso-responsable-ia.md
      - Validación de Modelos: gobernanza/procedimiento-validacion-modelos.md
      - Framework AISIA: gobernanza/framework-aisia.md
      - Privacidad y Datos: gobernanza/privacidad-datos.md
      - Checklist Seguridad: gobernanza/checklist-seguridad.md
    - Operating Model:
      - Modelo Operativo CoE: gobernanza/operating-model-coe.md
      - Plan de Comunicación: gobernanza/plan-comunicacion-coe.md
    - Métricas y Dashboards:
      - Dashboard Portfolio: metricas/dashboard-portfolio.md
      - Dashboard IMPACT: metricas/dashboard-impact.md
      - Dashboard Riesgos: metricas/dashboard-riesgos.md
      - Mi Proyecto: metricas/mi-proyecto.md
    - 📋 Anexos y Formularios:
      - Formulario Caso de Uso: annexes/anexo-a-formulario-caso-uso.md
      - Checklist AISIA: annexes/anexo-b-checklist-aisia.md
      - Matriz de Riesgos: annexes/anexo-c-matriz-riesgos.md
      - Plantillas de Documentación: annexes/anexo-d-plantillas.md
      - Protocolo Respuesta Incidentes: annexes/anexo-e-respuesta-incidentes.md
      - Directorio de Recursos: annexes/anexo-f-directorio.md

# Extra configuration
extra:
  generator: false
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dannyawf/gov-portal-full
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/banco
    - icon: fontawesome/solid/envelope
      link: mailto:coe-ia@banco.mx
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    
  consent:
    title: Consentimiento de cookies
    description: |
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias,
      así como para medir la efectividad de nuestra documentación y si los
      usuarios encuentran lo que buscan. Con su consentimiento, nos ayuda a
      mejorar nuestra documentación.
    actions:
      - accept
      - reject
      - manage
  
  version:
    provider: mike
    default: latest
  
  # Custom variables
  org:
    name: Banco XYZ
    coe_email: coe-ia@banco.mx
    helpdesk: helpdesk-ai@banco.mx
    
  platform:
    name: Nova-Cell
    version: 2.0
    
  metrics:
    framework: IMPACT
    dimensions: 6
    kpis: 24