_format_version: "3.0"
_transform: true

services:
  - name: auth
    url: http://supabase-auth:9999/
    routes:
      - name: auth-route
        paths:
          - /auth/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          exposed_headers:
            - X-Auth-Token
          max_age: 3600

  - name: rest
    url: http://supabase-db:5432/
    routes:
      - name: rest-route
        paths:
          - /rest/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
          exposed_headers:
            - X-Auth-Token
          max_age: 3600
      - name: key-auth
        config:
          key_names:
            - apikey
          hide_credentials: false

  - name: realtime
    url: http://supabase-realtime:4000/
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
          exposed_headers:
            - X-Auth-Token
          max_age: 3600

  - name: storage
    url: http://supabase-storage:5000/
    routes:
      - name: storage-route
        paths:
          - /storage/v1/
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          credentials: true
          headers:
            - Accept
            - Accept-Version
            - Content-Length
            - Content-MD5
            - Content-Type
            - Date
            - X-Auth-Token
            - Authorization
            - apikey
          exposed_headers:
            - X-Auth-Token
          max_age: 3600

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SERVICE_ROLE_KEY}

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin